In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# sentences

sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# define the vocablaury size

voc_size = 10000

In [5]:
# one hot representation

one_hot_repr = [one_hot(words,voc_size)for words in sent]


In [6]:
one_hot_repr

[[506, 9219, 1212, 7027],
 [506, 9219, 1212, 2407],
 [506, 8733, 1212, 1101],
 [6061, 6324, 6742, 332, 1065],
 [6061, 6324, 6742, 332, 6839],
 [6198, 506, 2754, 1212, 5129],
 [2183, 4, 8394, 332]]

In [8]:
# word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [9]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  506 9219 1212 7027]
 [   0    0    0    0  506 9219 1212 2407]
 [   0    0    0    0  506 8733 1212 1101]
 [   0    0    0 6061 6324 6742  332 1065]
 [   0    0    0 6061 6324 6742  332 6839]
 [   0    0    0 6198  506 2754 1212 5129]
 [   0    0    0    0 2183    4 8394  332]]


In [10]:
# feature representation

dim = 10


In [11]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 127ms/step


array([[[-0.02375025, -0.03451303, -0.02223467, -0.02194401,
          0.02753553, -0.0016981 , -0.03043584, -0.02680192,
          0.00180999,  0.04172398],
        [-0.02375025, -0.03451303, -0.02223467, -0.02194401,
          0.02753553, -0.0016981 , -0.03043584, -0.02680192,
          0.00180999,  0.04172398],
        [-0.02375025, -0.03451303, -0.02223467, -0.02194401,
          0.02753553, -0.0016981 , -0.03043584, -0.02680192,
          0.00180999,  0.04172398],
        [-0.02375025, -0.03451303, -0.02223467, -0.02194401,
          0.02753553, -0.0016981 , -0.03043584, -0.02680192,
          0.00180999,  0.04172398],
        [-0.02191038,  0.02559651,  0.04880047,  0.01677458,
          0.02321618,  0.02875084,  0.01986391, -0.02414184,
         -0.03854728,  0.01285866],
        [-0.00760939, -0.01452874, -0.01229854, -0.04989907,
         -0.00751247, -0.02931684,  0.03420443, -0.04876707,
          0.01477177, -0.02870615],
        [-0.04161661, -0.01320002, -0.01528066, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0,  506, 9219, 1212, 7027], dtype=int32)

In [15]:
model.predict(embedded_docs[[0]])

1/1 [==============================] - 0s 26ms/step


array([[[-0.02375025, -0.03451303, -0.02223467, -0.02194401,
          0.02753553, -0.0016981 , -0.03043584, -0.02680192,
          0.00180999,  0.04172398],
        [-0.02375025, -0.03451303, -0.02223467, -0.02194401,
          0.02753553, -0.0016981 , -0.03043584, -0.02680192,
          0.00180999,  0.04172398],
        [-0.02375025, -0.03451303, -0.02223467, -0.02194401,
          0.02753553, -0.0016981 , -0.03043584, -0.02680192,
          0.00180999,  0.04172398],
        [-0.02375025, -0.03451303, -0.02223467, -0.02194401,
          0.02753553, -0.0016981 , -0.03043584, -0.02680192,
          0.00180999,  0.04172398],
        [-0.02191038,  0.02559651,  0.04880047,  0.01677458,
          0.02321618,  0.02875084,  0.01986391, -0.02414184,
         -0.03854728,  0.01285866],
        [-0.00760939, -0.01452874, -0.01229854, -0.04989907,
         -0.00751247, -0.02931684,  0.03420443, -0.04876707,
          0.01477177, -0.02870615],
        [-0.04161661, -0.01320002, -0.01528066, -0.0